.TH man 1 "28 Sep 2016" "Version 5.*" "MKV Extractor Qt5 man"


.SH NOM
\fBMKV Extractor Qt5\fP - gui for extracte tracks into the MKV file.


.SH SYNOPSIS
\fBmkv-extractor-qt5\fP [ MKV File ]


.SH DESCRIPTION
\fBMKV Extractor Qt5\fP is a gui software to manipulate tracks into the MKV file with different softwares.
.br
Its purpose is not to concurencer \fIMKVMergeGui\fP but to supplement it.
.LP
Here are the possibilities by \fBMKV Extractor Qt5\fP :
.br
    - Extraction of the different tracks with \fIMKVExtract\fP.
.br
    - Modification of the tracks informations with \fIMKVMerge\fP.
.br
    - Ré-encapsulation of the tracks with \fIMKVMerge\fP.
.br
    - Boost of the audio files with \fIFFMpeg\fP or \fIAVConv\fP.
.br
    - Conversion of the audio files in AC3 with \fIFFMpeg\fP or \fIAVConv\fP.
.br
    - Conversion of the audio files in stereo with \fIFFMpeg\fP or \fIAVConv\fP.
.br
    - Modification of the bitrate of the audio files with \fIFFMpeg\fP or \fIAVConv\fP.
.br
    - Conversion of the subtitles SUB/IDX to SRT with \fIQtesseract5\fP (multi cpu mode).
.br
    - Check of the MKV file with \fIMKValidator\fP.
.br
    - Optimization of the MKV file with \fIMKClean\fP.


.SH INFOS
\fIMKVMergeGui\fP is available in English, French and  Czech partially.


.SH AUTEUR
\fITerence Belleguic\fP aka \fIHizo\fP <hizo@free.fr>
.br
Software page (Ubuntu-fr.org forum) : https://forum.ubuntu-fr.org/viewtopic.php?id=1508741
.br
The icon has been created from icons of the \fIOxygen\fP theme : https://techbase.kde.org/Projects/Oxygen
