.TH man 1 "28 Sep 2016" "Version 5.*" "Manuel de MKV Extractor Qt5"


.SH NOM
\fBMKV Extractor Qt5\fP - extracteur graphique de pistes de fichiers MKV.


.SH SYNOPSIS
\fBmkv-extractor-qt5\fP [ Fichier MKV ]


.SH DESCRIPTION
\fBMKV Extractor Qt5\fP est un logiciel graphique qui permet de manipuler le contenu de fichier MKV grace à différents logiciels.
.br
Son but n'est pas de concurencer \fIMKVMergeGui\fP mais de le compléter.
.LP
Voici les possibilités offertes par \fBMKV Extractor Qt5\fP :
.br
    - Extraction des différentes pistes avec \fIMKVExtract\fP.
.br
    - Modifications d'informations des pistes avec \fIMKVMerge\fP.
.br
    - Ré-encapsulage des pistes avec \fIMKVMerge\fP.
.br
    - Boost des fichiers audio avec \fIFFMpeg\fP ou \fIAVConv\fP.
.br
    - Conversion des fichiers audio en AC3 avec \fIFFMpeg\fP ou \fIAVConv\fP.
.br
    - Conversion des fichiers audio en stéréo avec \fIFFMpeg\fP ou \fIAVConv\fP.
.br
    - Modification du débit des fichiers audio avec \fIFFMpeg\fP ou \fIAVConv\fP.
.br
    - Convertion des sous-titres SUB/IDX en SRT avec \fIQtesseract5\fP (mode multi cpu).
.br
    - Vérification du fichier MKV avec \fIMKValidator\fP.
.br
    - Optimisation du fichier MKV avec \fIMKClean\fP.


.SH INFOS
\fIMKVMergeGui\fP est disponible en Français, Anglais et partiellement Tchèque.


.SH AUTEUR
\fITerence Belleguic\fP aka \fIHizo\fP <hizo@free.fr>
.br
Page du logiciel (forum Ubuntu-fr.org) : https://forum.ubuntu-fr.org/viewtopic.php?id=1508741
.br
L'icône a été créée depuis des icônes du théme \fIOxygen\fP : https://techbase.kde.org/Projects/Oxygen
