.TH MKV-EXTRACTOR-QT5 1 "JUNE 2016"
.SH NAME
mkv-extractor-qt5 - Graphical mkv demultiplexer

.SH SYNOPSIS
.B mkv\-extractor\-qt5 \fR[\fIfile\fR]
.PP
A matroska video (.mkv) can be given as input file through command line.

.SH DESCRIPTION
Features:
 * DTS to AC3 conversion via
.BR ffmpeg (1)
 * Automatic conversion from SUB to SRT via
.BR qtesseract5 (1)
 * Read and extract joined files
 * Extract and remux tracks
 * And more again

.SH AUTHOR
Terence Belleguic <hizo@free.fr>

.SH "SEE ALSO"
.BR mkvextract (1)

